### PR TITLE
Add android support

### LINKED ISSUE #10: `sb-posix:getpwnam` is not defined for Android
`nfiles` relies on `sb-posix:getpwnam` which is not defined for Android.

Any ideas on how to be able to run this library on Android?

```lisp
#-(or win32 android)
(macrolet ((define-obj-call (name arg type conv)
  ;; FIXME: this isn't the documented way of doing this, surely?
  (let ((lisp-name (intern (string-upcase name) :sb-posix)))
    `(progn
      (export ',lisp-name :sb-posix)
      (declaim (inline ,lisp-name))
      (defun ,lisp-name (,arg)
        (let ((r (alien-funcall (extern-alien ,name ,type) ,arg)))
          (if (null-alien r)
              nil
              (,conv r))))))))

(define-obj-call "getpwnam" login-name (function (* alien-passwd) (c-string :not-null t))
                 alien-to-passwd)
(define-obj-call "getpwuid" uid (function (* alien-passwd) uid-t)
                 alien-to-passwd)
(define-obj-call "getgrnam" login-name (function (* alien-group) (c-string :not-null t))
                 alien-to-group)
(define-obj-call "getgrgid" gid (function (* alien-group) gid-t)
                 alien-to-group)
) ; end MACROLET
```

### PR DESCRIPTION
**Pull request by aadcg**
Fixes #10.

### CODE REVIEW

**Comment by aartaka** [comment]
But wait, does SBCL have `:android` in `*features*` on Android? Have you checked? 

My comment in #10 is about ECL, just in case :)

**Comment by aadcg** [comment]
> But wait, does SBCL have :android in *features* on Android? Have you checked?

Yes, of course.

**Comment by aartaka** [comment]
Cool! Then I've nothing to complain about, feel free to merge!

**Comment by aadcg** [comment]
Merged via  0089ea2 and d146e4a.

Thanks.

**Pull request closed without merging**
